variables:
  TERRAFORM_VERSION: '1.5.5'
  AZURE_SUBSCRIPTION: 'fab7526b-56a5-4c43-9ba1-85eb890d86d5' # Only for reference
  RESOURCE_GROUP: 'taller1'
  CONTAINERAPPS_ENVIRONMENT: 'microservices-env'

stages:
- stage: Destroy_Existing
  displayName: 'Eliminar recursos existentes'
  jobs:
  - job: Destroy
    displayName: 'Eliminar Container Apps'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Eliminar Container Apps'
      inputs:
        azureSubscription: 'azure-terraform-connection' # Must match your service connection name
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          if az containerapp env show -n $(CONTAINERAPPS_ENVIRONMENT) -g $(RESOURCE_GROUP) &>/dev/null; then
            echo "Eliminando Container Apps..."
            apps=$(az containerapp list --resource-group $(RESOURCE_GROUP) --query "[].name" -o tsv)
            for app in $apps; do
              echo "Eliminando $app..."
              az containerapp delete --name $app --resource-group $(RESOURCE_GROUP) --yes
            done
          fi

- stage: Deploy_Infra
  displayName: 'Desplegar Infraestructura'
  dependsOn: Destroy_Existing
  jobs:
  - job: Terraform
    displayName: 'Ejecutar Terraform'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    
    # Either use the marketplace task (after installing extension):
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: $(TERRAFORM_VERSION)
        
    # OR use manual installation (uncomment below):
    # - script: |
    #     wget https://releases.hashicorp.com/terraform/$(TERRAFORM_VERSION)/terraform_$(TERRAFORM_VERSION)_linux_amd64.zip
    #     unzip terraform_$(TERRAFORM_VERSION)_linux_amd64.zip
    #     sudo mv terraform /usr/local/bin/
    #   displayName: 'Install Terraform manually'

    - task: AzureCLI@2
      displayName: 'Login Azure'
      inputs:
        azureSubscription: 'azure-terraform-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: az account show

    - script: |
        cd infra
        terraform init -input=false
        terraform validate
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init/Plan/Apply'