version: "3.8"

services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  auth-api:
    build:
      context: ./auth-api
    container_name: auth-api
    environment:
      - JWT_SECRET=PRFT
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=http://users-api:8083
    ports:
      - "8081:8081"
    depends_on:
      - users-api
    networks:
      - app-network

  users-api:
    build:
      context: ./users-api
    container_name: users-api
    environment:
      - JWT_SECRET=PRFT
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    networks:
      - app-network

  todos-api:
    build:
      context: ./todos-api
    container_name: todos-api
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=PRFT
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    ports:
      - "8085:8082"
    depends_on:
      - redis
      - auth-api
    networks:
      - app-network

  log-message-processor:
    build:
      context: ./log-message-processor
    container_name: log-message-processor
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CHANNEL=log_channel
    depends_on:
      - redis
    networks:
      - app-network
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8089:8080"
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8081/
      - TODOS_API_ADDRESS=http://todos-api:8082/
    depends_on:
      - auth-api
      - todos-api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
